# Generated by Django 6.1 on 2026-08-08 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('flow_intensity', models.CharField(blank=True, choices=[('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy')], max_length=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('user', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('symptom', models.CharField(choices=[('cramps', 'Cramps'), ('headache', 'Headache'), ('bloating', 'Bloating'), ('mood_swings', 'Mood Swings'), ('fatigue', 'Fatigue'), ('breast_tenderness', 'Breast Tenderness'), ('nausea', 'Nausea'), ('acne', 'Acne'), ('back_pain', 'Back Pain'), ('insomnia', 'Insomnia'), ('cravings', 'Cravings'), ('spotting', 'Spotting'), ('other', 'Other')], max_length=50)),
                ('severity', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='cycles.cyclelog')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
